name: Training Action
on: push
jobs:
  run-the-scripts:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3  
      - name: Build the app
        run: ci/build-app.sh
      - name: Test the app
        run: ci/unit-test-app.sh
  random-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Get random quote
        run: curl api.quotable.io/random | jq .content