name: JAVA CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USER }}
  docker_password: ${{ secrets.DOCKER_PW }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone repo
        uses: actions/checkout@v3 
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: . 
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: Download code
        uses: actions/checkout@v3 
        with:
          name: code
          path: .
      - name: Build the app
        run: ci/build-app.sh
      - name: Test the app
        run: ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
      - name: List Files
        run: ls .
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: build docker
        run: ci/build-docker.sh
      - name: push docker
        run: ci/push-docker.sh
  Random-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Get random quote
        run: curl api.quotable.io/random | jq .content